spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coolout}
    username: postgres
    password: admin
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
#  profiles:
#    active: initdb

bot:
  name: ${BOT_NAME:CooloutTestBot}
  token: ${BOT_TOKEN:1758715668:AAHjA366ZmYSSAU_SExSdtbljcFUA7TKb0U}

coolout:
  chat: ${COOLOUT_CHAT:-478940670}
