spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coolout}
    username: postgres
    password: admin
  jpa:
    database: postgresql
    show-sql: true
#    hibernate:
#      ddl-auto: update
#  profiles:
#    active: initdb

bot:
  name: ${BOT_NAME:CooloutTestBot}
  token: ${BOT_TOKEN:1682904051:AAHecSD2S9nqLUwgCn2YvQTG0Quqx2RLUCQ}

coolout:
  chat: ${COOLOUT_CHAT:-478940670}
